---
- name: Test playbook for EDA
  hosts: localhost

  tasks:
    - name: Show _hosts
      ansible.builtin.debug:
        var: _hosts

    - name: Show eventdata
      ansible.builtin.debug:
        var: eventdata.result

